### ISSUE TITLE
Input format

### ISSUE THREAD

**Issue by shifaspv** [auspicious3000/WaveNet-Enhancement#2]
Hi,
 In what dimension should I give the inputs to the function 'bawn_pr_multi_gpu_train.py' & 'bawn_ll_multi_gpu_train.py'. I know the input data has to be stored in HDF5 format, should I create my data as matrix with each wave files samples as the rows?

**Comment by auspicious3000** [comment]
The shape of all inputs is width * num_of_tokens, where widths are different for clean, noisy, and target.
Clean input and target are quantized. Noisy input is raw audio samples.
You need to create data matrix with appropriate shape and alignment. I used HDF5 just because my data matrix is created using Matlab.
I should mention all of these in Readme later.

**Comment by shifaspv** [comment]
First of all thanks for replay. have to clarify the above comments, 
what you meant by the 'num_of_tokens', is that the output space size (ie 256)? or simply the strength of my data set .

**Comment by auspicious3000** [comment]
num_of_tokens is the size of the data set, similar to "batch_size".
channel is the output space size you are referring to.

**Comment by heixi** [comment]
could you tell me how to create the input data?

**Comment by auspicious3000** [comment]
The clean input is the quantized audio ranging from 0 to 255.
The noisy input is the corresponding noisy version in raw audio samples.
